### PR TITLE
fix: use-plain-http not working on some envs

### LINKED ISSUE #292: use-plain-http option not working
### What steps will reproduce the bug?

1. Create network: `docker network create synctest`
2. Run the registry: `docker run -d --network synctest --network-alias registry registry:3`
3. Attempt to run the sync: `docker run --rm --user 0 -v $PWD/victoria-metrics-and-logs.yaml:/config.yaml --network synctest mirror.gcr.io/bitnami/charts-syncer:2.1.6 sync --config /config.yaml --from-date 2025-07-01 --use-plain-log --use-plain-http`

With `victoria-metrics-and-logs.yaml`:

```yaml
source:
  repo:
    kind: HELM
    url: https://victoriametrics.github.io/helm-charts
target:
  repo:
    kind: OCI
    url: http://registry:5000/victoriametrics
# Specifies the subset of charts to be synchronized
charts:
  - victoria-metrics-operator

skipArtifacts: true
skipImages: true
```

### What is the expected behavior?

Sync should work

### What do you see instead?

```
I1106 10:03:33.955580       1 sync.go:37] Using config file: "/config.yaml"
I1106 10:03:34.311327       1 section_logger.go:15] Loading charts
E1106 10:03:34.317539       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.56.1" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.317563       1 index.go:131] Failed processing victoria-metrics-operator:0.56.1 chart. The index will remain incomplete.
E1106 10:03:34.318655       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.56.0" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.318686       1 index.go:131] Failed processing victoria-metrics-operator:0.56.0 chart. The index will remain incomplete.
E1106 10:03:34.319318       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.55.3" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.319381       1 index.go:131] Failed processing victoria-metrics-operator:0.55.3 chart. The index will remain incomplete.
E1106 10:03:34.320068       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.55.2" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.320170       1 index.go:131] Failed processing victoria-metrics-operator:0.55.2 chart. The index will remain incomplete.
E1106 10:03:34.320711       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.55.1" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.320769       1 index.go:131] Failed processing victoria-metrics-operator:0.55.1 chart. The index will remain incomplete.
E1106 10:03:34.321375       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.55.0" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.321384       1 index.go:131] Failed processing victoria-metrics-operator:0.55.0 chart. The index will remain incomplete.
E1106 10:03:34.322053       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.54.1" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.322088       1 index.go:131] Failed processing victoria-metrics-operator:0.54.1 chart. The index will remain incomplete.
E1106 10:03:34.322822       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.54.0" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.322854       1 index.go:131] Failed processing victoria-metrics-operator:0.54.0 chart. The index will remain incomplete.
E1106 10:03:34.323672       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.53.0" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.323681       1 index.go:131] Failed processing victoria-metrics-operator:0.53.0 chart. The index will remain incomplete.
E1106 10:03:34.324311       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.52.1" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.324466       1 index.go:131] Failed processing victoria-metrics-operator:0.52.1 chart. The index will remain incomplete.
E1106 10:03:34.325269       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.52.0" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.325352       1 index.go:131] Failed processing victoria-metrics-operator:0.52.0 chart. The index will remain incomplete.
E1106 10:03:34.325943       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.51.4" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.325981       1 index.go:131] Failed processing victoria-metrics-operator:0.51.4 chart. The index will remain incomplete.
E1106 10:03:34.326706       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.51.3" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.326919       1 index.go:131] Failed processing victoria-metrics-operator:0.51.3 chart. The index will remain incomplete.
E1106 10:03:34.327591       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.51.2" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.327700       1 index.go:131] Failed processing victoria-metrics-operator:0.51.2 chart. The index will remain incomplete.
E1106 10:03:34.328270       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.51.1" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.328311       1 index.go:131] Failed processing victoria-metrics-operator:0.51.1 chart. The index will remain incomplete.
E1106 10:03:34.328857       1 index.go:156] unable to explore target repo to check "victoria-metrics-operator-0.51.0" chart: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
W1106 10:03:34.328892       1 index.go:131] Failed processing victoria-metrics-operator:0.51.0 chart. The index will remain incomplete.
W1106 10:03:34.329527       1 logger.go:33] There were some problems loading the information of the requested charts: failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
failed checking remote: Get "https://registry:5000/v2/": http: server gave HTTP response to HTTPS client
I1106 10:03:34.329562       1 logger.go:18] There are no charts out of sync!
I1106 10:03:34.329565       1 section_logger.go:36] There are no charts out of sync!
```

Clearly, the setting is not used, or I wouldn't see messages like "http: server gave HTTP response to HTTPS client"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tompizmor**
### Description of the change

This PR will make the go-containerregistry library to properly parse the OCI reference when the flag --use-plain-http is set

### Benefits

The --use-plain-http flag will work fine in more environments

### Possible drawbacks
 
None

### Applicable issues

  - fixes #292

### CODE REVIEW

File: pkg/client/repo/oci/oci.go [hunk 1]
```diff
@@ -353,24 +349,13 @@ func isHelmChartContentLayerMediaType(t string) bool {
 	return false
 }
 
-// ociReferenceExists checks if a given oci reference exists in the repository
-func ociReferenceExists(ociRef, username, password string) (bool, error) {
```
Comment (tompizmor) [inline pkg/client/repo/oci/oci.go:357]: this was unused

**Review by fjagugar — APPROVED** [review]

**Review by jotadrilo-work — APPROVED** [review]
